name: Rust

env:
  CARGO_TERM_COLOR: always

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name:  Install
      run:   |
            if [ "$RUNNER_OS" == "macOS" ]; then
                brew install libssh2;
                export OPENSSL_INCLUDE_DIR=`brew --prefix openssl`/include;
                export OPENSSL_LIB_DIR=`brew --prefix openssl`/lib;
            fi
      shell: bash
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
