name: Rust

env:
  CARGO_TERM_COLOR: always

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name:  Install macOS dependencies
      run:   |
            if [ "$RUNNER_OS" == "macOS" ]; then
                brew install libssh2;
                export OPENSSL_INCLUDE_DIR=`brew --prefix openssl`/include;
                export OPENSSL_LIB_DIR=`brew --prefix openssl`/lib;
            fi
      shell: bash
    - name: Install Linux dependencies
      run:   |
            if [ "$RUNNER_OS" == "Linux" ]; then
                sudo apt-get install -y openssl libssl-dev pkg-config zlib1g-dev
            fi
      shell: bash
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
